services:
  nodejs:
    build: ./app
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    working_dir: /app
    ports:
      - 1337:1337
    # command: npm i && npm run start
    # command: ./entry.sh
    command: sleep infinity

volumes:
  app_node_modules:
