services:
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: my_secret_password
      MARIADB_DATABASE: app_db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - 3306
    # volumes:
    #   - ./volumes/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80

  nodejs:
    build: ./app
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    working_dir: /app
    ports:
      - 1337:1337
    # command: npm i && npm run start
    # command: ./entry.sh
    command: sleep infinity

volumes:
  app_node_modules:
